### ISSUE TITLE
Demo cannot be compiled

### ISSUE THREAD

**Issue by greezi** [Mijick/Navigattie-Demo#2]
package 'navigattie' @ 9e043690ad53da6e6e4974513e98b4e894fce730 is using Swift tools version 5.8.0 but the installed version is 5.7.1 in https://github.com/Mijick/Navigattie

The Xcode version I am using is 14.2

**Comment by FulcrumOne** [comment]
Hi. Try to upload your Xcode to the newest version. It should help
